### PR TITLE
Add s390x support & Setup multi-arch travis-ci job

### PR DESCRIPTION
**Pull request by Siddhesh-Ghadi**
Add s390x support and migrate travis-ci job from vm based environment to lxd container environment.

### CODE REVIEW

**Comment by Siddhesh-Ghadi** [comment]
Please have a look. @roblourens

**Comment by roblourens** [comment]
...why? What is this for?

**Comment by ghatwala** [comment]
hey @roblourens  , so we need this to enable [eclipse/che-theia](https://github.com/eclipse/che-theia) builds on `s390x` arch which needs `ripgrep-prebuilt` invoked via https://github.com/microsoft/vscode-ripgrep/blob/master/lib/postinstall.js#L41. 

Once this PR is merged to enable `s390x` , we will be raising another one in `vscode-ripgrep` repo like - `arch === 's390x' ? 's390x-unknown-linux-gnu' `. Please let us know if you need more details to enable another arch just like you had enabled `ppc64le` in the past .

**Comment by roblourens** [comment]
Thanks, please give me this context up front, I don't just merge a PR with no explanation

**Comment by ghatwala** [comment]
@roblourens  - Acknowledged , will ensure we do that in future. Also can you please update [releases ](https://github.com/microsoft/ripgrep-prebuilt/releases) to have `s390x` tarball too. So that we can raise another PR to add `s390x` arch here -  https://github.com/microsoft/vscode-ripgrep/blob/master/lib/postinstall.js#L41.  ( cc- @kcrane )

**Comment by roblourens** [comment]
FYI, we will not be using Travis CI anymore, so the s390 and PPC architectures won't be built. If you need this, you could submit a PR that builds those archs in azure devops with the others

**Pull request merged**
